version: '3'
tasks:
  dev:
    desc: Run the docker image in development mode
    cmds:
    - poetry install
    - poetry run fastapi run server.py
  build:
    desc: Build the docker image
    cmds:
    - poetry export --without-hashes --format=requirements.txt > requirements.txt
    - docker build -t lab1-image .
  serve:
    desc: Run the docker image
    cmds:
    - docker run -p 5000:8000 -d --name lab1-container lab1-image
  kill:
    desc: Terminate the docker container
    cmds:
    - docker stop lab1-container
    - docker rm lab1-container
