FROM python:3.12-slim

COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app
COPY ./server-v1.py ./

ENTRYPOINT ["fastapi", "run", "server-v1.py", "--port", "8000"]